### ISSUE TITLE
cannot find symbol variable raw

### ISSUE THREAD

**Issue by rintran720** [aldebaran/qisdk-tutorials#5]
I have res/raw folder but still error

**Comment by nelsonogueh** [comment]
I am experiencing the same error too. Please help.

**Comment by tcruzcast** [comment]
Hello @rintran720 @ovovwe 

This issue happens since you're using Gradle build tools 3.2.0 or higher and one of your topics is not declared for the "default language". To fix this be sure that all of your topics are declared under the /res/raw folder.
For more information see: https://qisdk.softbankrobotics.com/sdk/doc/pepper-sdk/ch3_tools/dialog_editor.html#managing-default-and-multi-languages

Cheers!
